name: Build and Publish Images For Tag Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-?**"
env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  IMG_REGISTRY_REPO: limitador-operator
  OPERATOR_NAME: limitador-operator

jobs:
  build:
    name: Build and Push image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Mock image building
        run: |
          echo "Mocking image building"

      - name: Sleep for x seconds
        run: sleep 10
