name: Schedule nightly build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  release-date:
    name: GetDate
    runs-on: ubuntu-latest
    steps:
      - name: Mock release-date
        run: |
          echo "Mocking release-date"

      - name: Sleep for x seconds
        run: sleep 10
