name: Build Images

on:
  workflow_call:
    inputs:
      operatorVersion:
        description: Operator bundle version
        default: 0.0.0
        type: string
      operatorTag:
        description: Image tag
        default: latest
        type: string
      relatedImageLimitador:
        description: Related image of limitador
        default: quay.io/kuadrant/limitador:latest
        type: string
      channels:
        description: Bundle and catalog channels, comma separated
        default: preview
        type: string
      defaultChannel:
        description: Bundle default channel
        default: preview
        type: string
      quayImageExpiry:
        description: When to expire the built quay images. The time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively, from the time the image is built.
        default: never
        type: string
  workflow_dispatch:
    inputs:
      operatorVersion:
        description: Operator bundle version
        default: 0.0.0
        type: string
      operatorTag:
        description: Image tag
        default: latest
        type: string
      relatedImageLimitador:
        description: Related image of limitador
        default: quay.io/kuadrant/limitador:latest
        type: string
      channels:
        description: Bundle and catalog channels, comma separated
        default: preview
        type: string
      defaultChannel:
        description: Bundle default channel
        default: preview
        type: string
      quayImageExpiry:
        description: When to expire the built quay images. The time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively, from the time the image is built.
        default: never
        type: string

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  MAIN_BRANCH_NAME: main
  OPERATOR_NAME: limitador-operator
  QUAY_IMAGE_EXPIRY: ${{ inputs.quayImageExpiry }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Mock image building
        run: |
          echo "Mocking image building"

      - name: Sleep for x seconds
        run: sleep 10
