name: Release Operator

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Commit SHA, tag or branch name
        required: true
      limitadorOperatorVersion:
        description: Limitador Operator bundle version
        default: 0.0.0
        type: string
      limitadorVersion:
        description: Limitador service version
        default: 0.0.0
        type: string
      prerelease:
        description: Is the release a pre release?
        required: false
        type: boolean

jobs:
  build:
    name: Release operator
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "gitRef: ${{ inputs.gitRef }}"
          echo "limitadorOperatorVersion: ${{ inputs.limitadorOperatorVersion }}"
          echo "limitadorVersion: ${{ inputs.limitadorVersion }}"
          echo "prerelease: ${{ inputs.prerelease }}"
      - name: Sleep for 30 seconds
        run: sleep 30
