# Description: This workflow is used to release the Helm chart to the GitHub repository. The chart manifests should be already
# built with the target `helm-build` and the manifests changes already committed to the tag to be released.

name: Release Helm Chart
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      operatorTag:
          description: Operator bundle version tag
          default: v0.0.0
          type: string
jobs:
  chart_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Mock chart_release
      run: |
        echo "Mocking chart release"

    - name: Sleep for x seconds
      run: sleep 10
