name: Tests

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ '*' ]

  merge_group:
    types: [ checks_requested ]

  workflow_dispatch:

  schedule:
    - cron: "15 1 * * *"

jobs:
  pre-job:
    runs-on: ubuntu-latest
    name: Pre job checks
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - name: Mock tests
      run: |
        echo "Mocking tests"

    - name: Sleep for x seconds
      run: sleep 10
